const { GoogleGenAI } = require("@google/genai");
const { z } = require("zod");
const puppeteer = require("puppeteer");

const ai = new GoogleGenAI({
  apiKey: process.env.GOOGLE_GENAI_API_KEY,
});

const interviewReportSchema = z.object({
  matchScore: z.number().min(0).max(100),

  technicalQuestions: z
    .array(
      z.object({
        question: z.string(),
        intention: z.string(),
        answer: z.string(),
      }),
    )
    .min(10),

  behavioralQuestions: z
    .array(
      z.object({
        question: z.string(),
        intention: z.string(),
        answer: z.string(),
      }),
    )
    .min(5),

  skillGaps: z
    .array(
      z.object({
        skill: z.string(),
        severity: z.enum(["low", "medium", "high"]),
      }),
    )
    .min(3),

  preparationPlan: z
    .array(
      z.object({
        day: z.number(),
        focus: z.string(),
        tasks: z.array(z.string()).min(1),
      }),
    )
    .min(7),

  title: z.string(),
});

async function generateInterviewReport({
  resume,
  selfDescription,
  jobDescription,
}) {
  const prompt = `
You are an expert technical interviewer and career coach.

Analyze the candidate's resume, self-description, and job description.

Generate a complete interview preparation report.

You MUST return JSON with these EXACT property names:

matchScore
technicalQuestions
behavioralQuestions
skillGaps
preparationPlan
title

IMPORTANT RULES:

1. matchScore:
   - Must be a number between 0 and 100.
   - Example: 85
   - Do NOT return it as a string.

2. technicalQuestions:
   - Generate exactly 10 questions.
   - Each item MUST be an object:
     {
       "question": "...",
       "intention": "...",
       "answer": "..."
     }

3. behavioralQuestions:
   - Generate exactly 5 questions.
   - Each item MUST be an object:
     {
       "question": "...",
       "intention": "...",
       "answer": "..."
     }

4. skillGaps:
   - Generate exactly 3 skill gaps.
   - Each item MUST be:
     {
       "skill": "...",
       "severity": "low"
     }
   - severity MUST be exactly one of:
     "low", "medium", "high"
   - Do NOT use other values.

5. preparationPlan:
   - Generate exactly 7 days.
   - Each item MUST be:
     {
       "day": 1,
       "focus": "...",
       "tasks": ["...", "..."]
     }
   - day MUST be a number.

6. title:
   - Must be a string.
   - Use the job position as the title.
   - Example:
     "Full-Stack Developer Intern"

7. Use camelCase.
8. Do NOT use snake_case.
9. Do NOT omit any property.
10. Do NOT return empty arrays.

Candidate Resume:
${resume}

Candidate Self Description:
${selfDescription}

Job Description:
${jobDescription}
`;

  const response = await ai.models.generateContent({
    model: "gemini-3.6-flash",
    contents: prompt,
    config: {
      responseMimeType: "application/json",
    },
  });

  const result = JSON.parse(response.text);

  const validatedResult = interviewReportSchema.parse(result);

  return validatedResult;
}

async function generatePdfFromHtml(htmlContent){
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.setContent(htmlContent, {waitUntil: "networkidle0"})

    const pdfBuffer = await page.pdf({ format: "A4", margin: {
        top: "20mm",
        bottom: "20mm",
        left: "15mm",
        right: "15mm"
    } })

    await browser.close()

    return pdfBuffer
}

async function generateResumePdf({ resume, selfDescription, jobDescription }) {
  const resumePdfSchema = z.object({
    html: z
      .string()
      .describe(
        "The HTML content of the resume which can be converted to PDF using any library like puppeteer",
      ),
  });

  const prompt = `Generate resume for a candidate with the following details:
                        Resume: ${resume}
                        Self Description: ${selfDescription}
                        Job Description: ${jobDescription}

                        the response should be a JSON object with a single field "html" which contains the HTML content of the resume which can be converted to PDF using any library like puppeteer.
                        The resume should be tailored for the given job description and should highlight the candidate's strengths and relevant experience. The HTML content should be well-formatted and structured, making it easy to read and visually appealing.
                        The content of resume should be not sound like it's generated by AI and should be as close as possible to a real human-written resume.
                        you can highlight the content using some colors or different font styles but the overall design should be simple and professional.
                        The content should be ATS friendly, i.e. it should be easily parsable by ATS systems without losing important information.
                        The resume should not be so lengthy, it should ideally be 1-2 pages long when converted to PDF. Focus on quality rather than quantity and make sure to include all the relevant information that can increase the candidate's chances of getting an interview call for the given job description.
                    `;

  const response = await ai.models.generateContent({
    model: "gemini-3.6-flash",
    contents: prompt,
    config: {
      responseMimeType: "application/json",
    },
  });

  const result = JSON.parse(response.text);

  const validatedResult = resumePdfSchema.parse(result);

const pdfBuffer = await generatePdfFromHtml(validatedResult.html);
  return pdfBuffer
}

module.exports = {
    generateInterviewReport,
    generateResumePdf
};
